FROM localhost/rocky9:latest
USER root:root
RUN dnf install -y epel-release
RUN /usr/bin/crb enable
RUN dnf install -y GraphicsMagick make gcc-c++
RUN useradd -rmd /opt/rocketchat rocketchat
RUN usermod -L rocketchat
RUN curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
RUN tar -xzf /tmp/rocket.chat.tgz -C /opt --transform s/bundle/rocketchat/
RUN chown -R rocketchat:rocketchat /opt/rocketchat
RUN rm -f /tmp/rocket.chat.tgz
USER rocketchat:rocketchat
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
RUN \. "$HOME/.bashrc" && nvm install 14
RUN cd /opt/rocketchat/programs/server && \. "$HOME/.bashrc" && npm install
#USER root:root
#RUN mv /tmp/bundle/.[a-zA-Z0-9]* /opt/rocketchat/.
#RUN mv /tmp/bundle/* /opt/rocketchat/.
#RUN rmdir /tmp/bundle
#RUN chown -R rocketchat:rocketchat /opt/rocketchat
